<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SltaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sltas = [
            'SMA LAIN-LAIN',
            'SMA 1 CILEUNGSI',
            'SMAN 4 CIMAHI',
            'SMKN 1 CIMAHI',
            'SMAN 1 BALEENDAH',
            'SMA LABORATORIUM UPI',
            'SMKN 1 KOTA BLITAR',
            'SMAN 5 BUKITTINGGI',
            'SMAN 19 BANDUNG',
            'SMAN 1 CILEUNYI',
            'SMAN 2 TAROGONG KIDUL / SMAN 6 GARUT',
            'MAN 2 PEKANBARU',
            'SMKN 11 BANDUNG',
            'SMAN 1 Padalarang',
            'SMAN 1 CICALENGKA',
            'SMAN 22 BANDUNG',
            'SMAN 1 PALABUHAN RATU',
            'SMKN 1 PURWAKARTA',
            'SMKN 4 BANDUNG',
            'MAS MULTI TEKNIK ASIH PUTERA CIMAHI',
            'MAN SUBANG',
            'SMAN 1 BANDUNG',
            'SMAN 1 SUBANG',
            'SMAN 13 BANDUNG',
            'SMAN 1 MAJALENGKA',
            'SMAN 5 CIMAHI',
            'SMAN 14 BANDUNG',
            'SMAN 3 KLATEN',
            'SMAN 1 PANGALENGAN',
            'SMAN 1 RANGKASBITUNG',
            'SMAN 2 CIMAHI',
            'SMA NEGERI 1 TALANG UBI',
            'SMAN 1 TAROGONG KIDUL GARUT/SMAN 1 GARUT',
            'MA PERSIS 3 PAMEUNGPEUK',
            'SMKN 2 BANDUNG',
            'SMAN 8 BANDUNG',
            'SMA PLUS MERDEKA SOREANG',
            'SMA PASUNDAN 8',
            'SMAN 1 Ngamprah',
            'SMAN 5 PAMEKASAN',
            'SMAN 1 MARGAHAYU',
            'SMA PLUS ASSALAAM DAYEUHKOLOT',
            'SMAN 11 BANDUNG',
            'SMAN 1 PLUMBON',
            'SMA SUMATERA 40 NO. 2',
            'SMAN 2 KUDUS',
            'MAN 1 BOGOR',
            'SMAN 1 LELES / SMAN 2 GARUT',
            'SMA ISLAM CIPASUNG',
            'SMEA Muh., Sragen',
            'SMAN 3 TEGAL',
            'SMKN 13 BANDUNG',
            'SMAN 2 KS',
            'SMA ANGKASA 1',
            'SMAN 1 KATAPANG',
            'SMK (STM) N 5 SEMARANG',
            'SMK TI PEMBANGUNAN CIMAHI',
            'MA LAIN-LAIN',
            'SMAN 1 Batujajar',
            'SMAN 2 TARUTUNG',
            'MAN 2 TANJUNG KARANG',
            'SMAN 1 KOTA SERANG',
            'MAN 1 KOTA BANDUNG',
            'SMAN 6 CIMAHI',
            'SMAN 1 DEPOK',
            'SMAN 12 BANDUNG',
            'SMK LAIN-LAIN',
            'SMAN 24 BANDUNG',
            'SMAN 1 CIWIDEY',
            'SMAN 23 BANDUNG',
            'SMK ANGKASA',
            'SMA NEGERI 2 LEMBANG',
            'SMAN 1 Cipatat',
            'SMKN 4 Padalarang',
            'SMA MUHAMMADIYAH 4',
            'MAN 2 KOTA BANDUNG',
            'SMAN 2 BANDUNG',
            'SMAN 1 LEMAHABANG',
            'SMKN PALASAH',
            'SMK ICB CINTA NIAGA SMEA',
            'SMAN 1 Cililin',
            'MAS HUSNUL KHOTIMAH',
            'SMAN 1 Cisarua',
            'SMAN 7 BANDUNG',
            'SMAN 6 BANDUNG',
            'SMAN 9 KODYA BANDUNG',
            'SMAN 1 CIPARAY',
            'SMAN 1 MAJALAYA',
            'SMA ALFA CENTAURI',
            'SMAN 113 JAKARTA',
            'SMA HAYATAN THAYYIBAH',
            'SMAN 9 Garut',
            'SMAN 1 KUNINGAN',
            'SMAN 1 RANCAEKEK',
            'MA Sumur Bandung Cililin',
            'SMAN 3 BANDUNG',
            'SMAN 18 Garut',
            'SMAN 6 BEKASI',
            'SMAN 1 CIBADAK',
            'SMK Mahardika Batujajar',
            'SMAN 1 TARAJU',
            'SMAN 18 BANDUNG',
            'MA PERSIS KATAPANG',
            'MAN I GARUT',
            'SMAN 1 CIKARANG UTARA',
            'SMA ANGKASA MARGAHAYU',
            'SMAN 10 BANDUNG',
            'SMA AL MUTTAQIN FULLDAY SCHOOL TASIKMALAYA',
            'SMA MEDINA',
            'MAS PERSIS',
            'SMK TARUNA BANGSA',
            'SMAN 4 BANDUNG',
            'SMKN 1 KATAPANG',
            'SMAN 21 BANDUNG',
            'SMKN 1 CIANJUR',
        ];

        // Remove duplicates and sort
        $sltas = array_unique($sltas);
        sort($sltas);

        foreach ($sltas as $nama_slta) {
            DB::table('slta')->insert([
                'nama_slta_resmi' => $nama_slta,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
